// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopicDomain.Infrastructure.Database.DBContext;

#nullable disable

namespace TopicDomain.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250721074312_intitiate")]
    partial class intitiate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TopicDomain.Infrastructure.Database.Models.TopicModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sourse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("TopicDomain.Infrastructure.Database.Models.TopicModel", b =>
                {
                    b.HasOne("TopicDomain.Infrastructure.Database.Models.TopicModel", "Parent")
                        .WithMany("SubTopic")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TopicDomain.Infrastructure.Database.Models.TopicModel", b =>
                {
                    b.Navigation("SubTopic");
                });
#pragma warning restore 612, 618
        }
    }
}
