// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserRealetionShipDomain.Infrastructure.DataBase.DBContext;

#nullable disable

namespace UserRealetionShipDomain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserRealetionShipDomain.Infrastructure.DataBase.Model.SaveReadingListModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaveReadingListId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SaveAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "SaveReadingListId");

                    b.ToTable("SaveReadingList");
                });

            modelBuilder.Entity("UserRealetionShipDomain.Infrastructure.DataBase.Model.UserBlockModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlockId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BlockAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "BlockId");

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("UserRealetionShipDomain.Infrastructure.DataBase.Model.UserFollowModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FollowAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "FollowId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("UserRealetionShipDomain.Infrastructure.DataBase.Model.UserMuteModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MuteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("MuteAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "MuteId");

                    b.ToTable("UserMute");
                });
#pragma warning restore 612, 618
        }
    }
}
