// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResponceDomain.Infrastructure.DataBase.DBContex;

#nullable disable

namespace ResponceDomain.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResponceDomain.Infrastructure.DataBase.Models.ClapsToResponceOfUsersModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResponceId")
                        .HasColumnType("int");

                    b.Property<int>("ClapsCount")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ResponceId");

                    b.HasIndex("ResponceId");

                    b.ToTable("Claps");
                });

            modelBuilder.Entity("ResponceDomain.Infrastructure.DataBase.Models.ResponceModel", b =>
                {
                    b.Property<int>("ResponceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponceId"));

                    b.Property<int?>("BaseResponseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReaderTypeEnum")
                        .HasColumnType("int");

                    b.Property<string>("TextOfReply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponceId");

                    b.HasIndex("BaseResponseId");

                    b.ToTable("Responces");
                });

            modelBuilder.Entity("ResponceDomain.Infrastructure.DataBase.Models.ClapsToResponceOfUsersModel", b =>
                {
                    b.HasOne("ResponceDomain.Infrastructure.DataBase.Models.ResponceModel", "Responce")
                        .WithMany("ClapsToResponceOfUsersModels")
                        .HasForeignKey("ResponceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responce");
                });

            modelBuilder.Entity("ResponceDomain.Infrastructure.DataBase.Models.ResponceModel", b =>
                {
                    b.HasOne("ResponceDomain.Infrastructure.DataBase.Models.ResponceModel", "BaseResponce")
                        .WithMany("ChildResponses")
                        .HasForeignKey("BaseResponseId");

                    b.Navigation("BaseResponce");
                });

            modelBuilder.Entity("ResponceDomain.Infrastructure.DataBase.Models.ResponceModel", b =>
                {
                    b.Navigation("ChildResponses");

                    b.Navigation("ClapsToResponceOfUsersModels");
                });
#pragma warning restore 612, 618
        }
    }
}
